'''
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''

class Solution:
    def findTheDifference(self, s, t):
        s_counter=collections.Counter(s)
        t_counter=collections.Counter(t)
        for ch in t_counter-s_counter:
            return ch

        """
        :type s: str
        :type t: str
        :rtype: str
        """
